# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs'
source ‘https://github.com/momo13014/Specs’

platform :ios, '9.0'

target 'Today' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for Today
  pod ‘SDNetworking’
  pod 'AFNetworking', '~> 2.5'
  pod 'ReactiveCocoa', '~> 2.5'
  pod 'SDWebImage'
  # leanCloud
  pod 'AVOSCloud', '~>4.0.0'               # 数据存储、短信、云引擎调用等基础服务模块
  pod 'AVOSCloudIM', '~>4.0.0'             # 实时通信模块
  pod 'AVOSCloudCrashReporting', '~>4.0.0' # 错误报告模块
  
  pod 'DateTools', '~> 2.0.0'

end
